export enum ActionType {
	PRELIMINARY_ADD_SUCCESS = 'PRELIMINARY_ADD_SUCCESS',
	PRELIMINARY_ADD_ERROR = ' PRELIMINARY_ADD_ERROR',
	PRELIMINARY_EDIT_SUCCESS = ' PRELIMINARY_EDIT_SUCCESS',
	PRELIMINARY_EDIT_ERROR = ' PRELIMINARY_EDIT_ERROR',
	GET_PRELIMINARY_SUCCESS = 'GET_PRELIMINARY_SUCCESS',
	GET_PRELIMINARY_ERROR = 'GET_PRELIMINARY_ERROR',
	UPDATE_PRELIMINARY_STATE = 'UPDATE_PRELIMINARY_STATE',
	RESET_PRELIMINARY_STATE = 'RESET_PRELIMINARY_STATE',
	SET_LOADING_TRUE = 'SET_LOADING_TRUE'
}
