export const ProjectFormProps = {
  name: 'Test',
  contractorId: 1,
  companyId: 1,
  headOfProject: 'Test',
  projectOwner: 'Test',
  projectManager: 'Test',
  pmHasExperience: true,
  scope: 'Test',
  cnNumber: 2,
  status: 1,
  engagementId: 2,
  countryId: 3,
  currencyId: 1,
  probabilityOfWinning: 'Test',
  approxValue: 'Test',
  contractTypeId: 'Test',
  cdmNotifiable: true,
  firstAssetWorkedOn: 0,
  secondAssetWorkedOn: 0,
  thirdAssetWorkedOn: 0,
  comment: 'Test'
};
