export enum ActionType {
  PROJECT_OVERVIEW_FORM_ADD_SUCCESS = 'PROJECT_OVERVIEW_FORM_ADD_SUCCESS',
  PROJECT_OVERVIEW_FORM_EDIT_SUCCESS = 'PROJECT_OVERVIEW_FORM_EDIT_SUCCESS',
  PROJECT_OVERVIEW_FORM_ERROR = 'PROJECT_OVERVIEW_FORM_ERROR',
  GET_ADDITIONALS_DETAILS_SUCCESS = 'GET_ADDITIONALS_DETAILS_SUCCESS',
  GET_ADDITIONALS_DETAILS_ERROR = 'GET_ADDITIONALS_DETAILS_ERROR'
}
