export enum ActionType {
  PROJECT_OVERVIEW_FORM_ADD_SUCCESS = 'PROJECT_OVERVIEW_FORM_ADD_SUCCESS',
  PROJECT_OVERVIEW_FORM_EDIT_SUCCESS = 'PROJECT_OVERVIEW_FORM_EDIT_SUCCESS',
  PROJECT_OVERVIEW_FORM_ERROR = 'PROJECT_OVERVIEW_FORM_ERROR',
  GET_ADDITIONALS_DETAILS_SUCCESS = 'GET_ADDITIONALS_DETAILS_SUCCESS',
  GET_ADDITIONALS_DETAILS_ERROR = 'GET_ADDITIONALS_DETAILS_ERROR',
  RESET_PROJECT_OVERVIEW_STATE = 'RESET_PROJECT_OVERVIEW_STATE',
  CHANGE_PROJECT_STATUS_TO_BID_LOST_SUCCESS = 'CHANGE_PROJECT_STATUS_TO_BID_LOST_SUCCESS',
  CHANGE_PROJECT_STATUS_TO_BID_LOST_ERROR='CHANGE_PROJECT_STATUS_TO_BID_LOST_ERROR',
  CHANGE_PROJECT_STATUS_TO_ON_HOLD_SUCCESS = 'CHANGE_PROJECT_STATUS_TO_ON_HOLD_SUCCESS',
  CHANGE_PROJECT_STATUS_TO_ON_HOLD_ERROR='CHANGE_PROJECT_STATUS_TO_ON_HOLD_ERROR',
  REACTIVATE_PROJECT_SUCCESS='REACTIVATE_PROJECT_SUCCESS',
  REACTIVATE_PROJECT_ERROR='REACTIVATE_PROJECT_ERROR'
}
