export enum ActionType {
	PROJECT_OVERVIEW_FORM_ADD_SUCCESS = 'PROJECT_OVERVIEW_FORM_ADD_SUCCESS',
	PROJECT_OVERVIEW_FORM_EDIT_SUCCESS = 'PROJECT_OVERVIEW_FORM_EDIT_SUCCESS',
	PROJECT_OVERVIEW_FORM_ERROR = 'PROJECT_OVERVIEW_FORM_ERROR',
	GET_ADDITIONALS_DETAILS_SUCCESS = 'GET_ADDITIONALS_DETAILS_SUCCESS',
	GET_ADDITIONALS_DETAILS_ERROR = 'GET_ADDITIONALS_DETAILS_ERROR',
	RESET_PROJECT_OVERVIEW_STATE = 'RESET_PROJECT_OVERVIEW_STATE',
	BIND_PROJECT_APPROVAL_INITIAL_DATA = 'BIND_PROJECT_APPROVAL_INITIAL_DATA',
	GET_PROJECT_ACTIVITIES_SUCCESS = 'GET_PROJECT_ACTIVITIES_SUCCESS',
	GET_PROJECT_ACTIVITIES_ERROR = 'GET_PROJECT_ACTIVITIES_ERROR',
	RESET_PROJECT_OVERVIEW_NOTIFIER = 'RESET_PROJECT_OVERVIEW_NOTIFIER',
	SET_LOADING_TRUE = 'SET_LOADING_TRUE'
}
