export enum ActionType {
  DYNAMIC_CONTRACT_DATA_GET_SUCCESS = 'DYNAMIC_CONTRACT_DATA_GET_SUCCESS',
  DYNAMIC_CONTRACT_DATA_GET_ERROR = 'DYNAMIC_CONTRACT_DATA_GET_ERROR',
  DYNAMIC_COMPANY_DATA_GET_SUCCESS = 'DYNAMIC_COMPANY_DATA_GET_SUCCESS',
  DYNAMIC_COMPANY_DATA_GET_ERROR = 'DYNAMIC_COMPANY_DATA_GET_ERROR',
  DYNAMIC_OTHER_CONTRACT_SUCCESS = 'DYNAMIC_OTHER_CONTRACT_SUCCESS',
  DYNAMIC_OTHER_COMPANY_SUCCESS = 'DYNAMIC_OTHER_COMPANY_SUCCESS',
  DYNAMIC_SUB_CONTRACTOR_DATA_GET_SUCCESS = 'DYNAMIC_SUB_CONTRACTOR_DATA_GET_SUCCESS',
  DYNAMIC_SUB_CONTRACTOR_DATA_GET_ERROR = 'DYNAMIC_SUB_CONTRACTOR_DATA_GET_ERROR',
  DYNAMIC_OTHER_SUB_CONTRACTOR_SUCCESS = 'DYNAMIC_OTHER_SUB_CONTRACTOR_SUCCESS',
}
