export enum ActionType {
  AD_HOP_GET_SUCCESS = 'AD_HOP_GET_SUCCESS',
  AD_HOP_GET_ERROR = 'AD_HOP_GET_ERROR',
  AD_PO_GET_SUCCESS = 'AD_PO_GET_SUCCESS',
  AD_PO_GET_ERROR = 'AD_PO_GET_ERROR',
  AD_PM_GET_SUCCESS = 'AD_PM_GET_SUCCESS',
  AD_PM_GET_ERROR = 'AD_PM_GET_ERROR',
  AD_HOP_GET_OTHER = 'AD_HOP_GET_OTHER',
  AD_PO_GET_OTHER = 'AD_PO_GET_OTHER',
  AD_PM_GET_OTHER = 'AD_PM_GET_OTHER'
}
