export enum ActionType {
  USER_SERVICE_GET_SUCCESS = 'USER_SERVICE_GET_SUCCESS',
  USER_SERVICE_GET_ERROR = 'USER_SERVICE_GET_ERROR',
  USER_NAMES_FOR_EMAILSSERVICE_GET_SUCCESS = 'USER_NAMES_FOR_EMAILSSERVICE_GET_SUCCESS',
  USER_NAMES_FOR_EMAILS_SERVICE_GET_ERROR = 'USER_NAMES_FOR_EMAILS_SERVICE_GET_ERROR',
  CURRENT_USER_PROFILE_FOR_EMAILSSERVICE_GET_SUCCESS = 'CURRENT_USER_PROFILE_FOR_EMAILSSERVICE_GET_SUCCESS',
}
