export enum ActionType {
  SUB_CONTRACTOR_FORM_ADD_SUCCESS = 'SUB_CONTRACTOR_FORM_ADD_SUCCESS',
  SUB_CONTRACTOR_FORM_EDIT_SUCCESS = 'SUB_CONTRACTOR_FORM_EDIT_SUCCESS',
  SUB_CONTRACTOR_FORM_ERROR = 'SUB_CONTRACTOR_FORM_ERROR',
  GET_SUB_CONTRACTOR_SUCCESS = 'GET_SUB_CONTRACTOR_SUCCESS',
  GET_SUB_CONTRACTOR_ERROR = 'GET_SUB_CONTRACTOR_ERROR',
  RESET_SUB_CONTRACTOR_STATE = 'RESET_SUB_CONTRACTOR_STATE',
  RESET_SUB_CONTRACTOR_NOTIFIER = 'RESET_SUB_CONTRACTOR_NOTIFIER',
  SET_LOADING_TRUE = 'SET_LOADING_TRUE',
  SUB_CONTRACTOR_ADD_NEW_ACTIVITY = "SUB_CONTRACTOR_ADD_NEW_ACTIVITY"
}
