export enum ActionType {
  USER_PREFERENCES_FORM_ADD_SUCCESS = 'USER_PREFERENCES_FORM_ADD_SUCCESS',
  USER_PREFERENCES_FORM_EDIT_SUCCESS = 'USER_PREFERENCES_FORM_EDIT_SUCCESS',
  USER_PREFERENCES_GET_SUCCESS = 'USER_PREFERENCES_GET_SUCCESS',
  USER_PREFERENCES_FORM_ERROR = 'USER_PREFERENCES_FORM_ERROR',
  RESET_USER_PREFERENCES_STATE = 'RESET_USER_PREFERENCES_STATE',
  SET_LOADING_TRUE = 'SET_LOADING_TRUE'
}
