export enum ActionType {
  USER_PREFERENCES_FORM_ADD_SUCCESS = 'USER_PREFERENCES_FORM_ADD_SUCCESS',
  USER_PREFERENCES_FORM_EDIT_SUCCESS = 'USER_PREFERENCES_FORM_EDIT_SUCCESS',
  USER_PREFERENCES_GET_SUCCESS = 'USER_PREFERENCES_GET_SUCCESS',
  USER_PREFERENCES_FORM_ERROR = 'USER_PREFERENCES_FORM_ERROR'
}
