export enum ActionType {
  USER_PREFERENCES_FORM_ADD_SUCCESS = 'PROJECT_OVERVIEW_FORM_ADD_SUCCESS',
  USER_PREFERENCES_FORM_EDIT_SUCCESS = 'PROJECT_OVERVIEW_FORM_EDIT_SUCCESS',
  USER_PREFERENCES_FORM_ERROR = 'PROJECT_OVERVIEW_FORM_ERROR'
}
