export enum ActionType {
  LOOKUP_PROJECT_STATUS_GET_SUCCESS = 'LOOKUP_PROJECT_STATUS_GET_SUCCESS',
  LOOKUP_PROJECT_STATUS_GET_ERROR = 'LOOKUP_PROJECT_STATUS_GET_ERROR',
  LOOKUPS_GET_SUCCESS = 'LOOKUPS_GET_SUCCESS',
  LOOKUPS_GET_ERROR = 'LOOKUPS_GET_ERROR',
  GET_ALL_CURRENCIES_SUCCESS = 'GET_ALL_CURRENCIES_SUCCESS',
  GET_ALL_CURRENCIES_ERROR = 'GET_ALL_CURRENCIES_ERROR',
  GET_ALL_LANGUAGE_SUCCESS = 'GET_ALL_LANGUAGE_SUCCESS',
  GET_ALL_LANGUAGE_ERROR = 'GET_ALL_LANGUAGE_ERROR',
  GET_ALL_COUNTRIES_SUCCESS = 'GET_ALL_COUNTRIES_SUCCESS',
  GET_ALL_COUNTRIES_ERROR = 'GET_ALL_COUNTRIES_ERROR',
}
