export enum ActionType {
  LOOKUP_PROJECT_STATUS_GET_SUCCESS = 'LOOKUP_PROJECT_STATUS_GET_SUCCESS',
  LOOKUP_PROJECT_STATUS_GET_ERROR = 'LOOKUP_PROJECT_STATUS_GET_ERROR',
  GET_ALL_CURRENCIES_SUCCESS = 'GET_ALL_CURRENCIES_SUCCESS',
  GET_ALL_CURRENCIES_ERROR = 'GET_ALL_CURRENCIES_ERROR'
}
