export enum ActionType {
	DISCOUNT_FORM_DATA_ADD = 'DISCOUNT_FORM_DATA_ADD',
	DISCOUNT_FORM_DATA_ERROR = 'DISCOUNT_FORM_DATA_ERROR',
	DISCOUNT_FORM_DATA_EDIT = 'DISCOUNT_FORM_DATA_EDIT',
	RESET_DISCOUNT_FORM_STATE = 'RESET_DISCOUNT_FORM_STATE',
	RESET_DISCOUNT_FORM_STATE_NOTIFIER = 'RESET_DISCOUNT_FORM_STATE_NOTIFIER',
	DISCOUNT_FORM_DATA_GET = 'DISCOUNT_FORM_DATA_GET',
	DISCOUNT_FORM_DATA_GET_ERROR = 'DISCOUNT_FORM_DATA_GET_ERROR'
}
