export enum ActionType {
  DISCOUNT_FORM_DATA_ADD = 'DISCOUNT_FORM_DATA_ADD',
  DISCOUNT_FORM_DATA_ERROR = 'DISCOUNT_FORM_DATA_ERROR',
  DISCOUNT_FORM_DATA_EDIT = 'DISCOUNT_FORM_DATA_EDIT',
   RESET_DISCOUNT_FORM_STATE = 'RESET_DISCOUNT_FORM_STATE'
}
