import moment from 'moment';
export const formdata = {
  projectAddDetailId: 'Test',
  projectId: 'Test',
  mainContractor: 'Test',
  enquiryReceivedFrom: 'Test',
  potentialCustomer: 'Test',
  enquiryTypeId: '1',
  creditCheckResult: 'Test',
  siteAddress: 'Test',
  cdmNotifiable: true,
  formOfContract: 'Test',
  retention: 'Test',
  liquidatedDamages: 'Test',
  insurance: 'Test',
  workTypeId: '1',
  commenceDate: moment().toString(),
  completionDate: moment().toString(),
  milestones: 'Test',
  firstValuationDate: moment().toString(),
  finalAccountDate: moment().toString(),
  valuationIntervals: 'Test',
  paymentTerms: 'Test',
  isProjectLive: false,
  comments: 'Test',
  authorizedByHop: 'Test',
  budget: 'Test',
  authorizedBy: 'Test',
  authorizedBySecond: 'Test',
  authorizedByThird: 'Test'
};
