import Enzyme from 'enzyme';
import EnzymeAdapter from 'enzyme-adapter-react-16';

Enzyme.configure({
    adapter: new EnzymeAdapter()
});

window.Config = {
    REACT_APP_AUTH_INSTANCE: 'TEST_REACT_APP_AUTH_INSTANCE',
    REACT_APP_AUTH_TENANT: 'TEST_REACT_APP_AUTH_TENANT',
    REACT_APP_AUTH_SIGNINPOLICY: 'TEST_REACT_APP_AUTH_SIGNINPOLICY',
    REACT_APP_AUTH_APPID: 'TEST_REACT_APP_AUTH_APPID',
    REACT_APP_INSIGHTS_KEY: 'TEST_REACT_APP_INSIGHTS_KEY',
    REACT_APP_MIDDLETIER_URL: 'TEST_REACT_APP_MIDDLETIER_URL',
    REACT_APP_GATEWAY_URL: 'TEST_REACT_APP_GATEWAY_URL'
};

