export enum ActionType {
    PROJECT_PIPELINE_GRID_ERROR = 'PROJECT_PIPELINE_GRID_ERROR',
    PROJECT_PIPELINE_GRID_DETAILS = 'PROJECT_PIPELINE_GRID_DETAILS',
    GET_PROJECT_CHART_SUMMARY_SUCCESS = 'GET_PROJECT_CHART_SUMMARY_SUCCESS',
    GET_PROJECT_CHART_SUMMARY_ERROR = 'GET_PROJECT_CHART_SUMMARY_ERROR',
    SET_LOADING_TRUE = "SET_LOADING_TRUE"
}
