# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
      - release/*
  paths:
    include:
      - web/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'npm install'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: web
    verbose: false
    customCommand: 'npm run build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'web/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/web.zip'
    replaceExistingArchive: true
  displayName: "pack build"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: "Drop artifacts"